import type { Dungeon, GameClass, LeaderboardRecord } from './types.js'

const frontendDungeons: Dungeon[] = [
  {
    id: 'fe-01',
    order: 1,
    type: 'standard',
    title: 'Il Badge del Carrello Silenzioso',
    problem: 'State mutato direttamente, niente rerender del badge carrello',
    scenario:
      'Nel checkout mobile il badge quantità non si aggiorna, anche se i prodotti cambiano davvero.',
    prompt: 'Qual è la correzione più affidabile?',
    options: [
      { id: 'a', label: 'Creare un nuovo stato immutabile e usare il setter corretto', type: 'correct' },
      { id: 'b', label: 'Forzare il rerender del componente padre', type: 'seducing_wrong' },
      { id: 'c', label: 'Aggiungere un timeout prima del render', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'vista-dom',
    hintText: 'Il badge non manca di vista: manca un segnale vero di cambiamento.',
    successTitle: 'Hai riaccordato lo stato del carrello.',
    successBody:
      'In React il cambiamento affidabile passa da un nuovo riferimento di stato. La mutazione diretta non garantisce rerender corretto.',
    wrongTitle: 'Hai scelto una scorciatoia seducente.',
    wrongBody:
      'Forzare il rerender o inserire attese maschera il sintomo, ma non corregge la causa del problema.',
    incompleteBody:
      'L idea aiuta a ridurre il rumore, ma non garantisce una base robusta quando lo stato evolve davvero.',
    reportTags: ['react-state', 'immutability', 'ui-reactivity'],
  },
  {
    id: 'fe-02',
    order: 2,
    type: 'standard',
    title: 'La Libreria del Bundle Vorace',
    problem: 'Bundle iniziale troppo pesante e caricamento inutile di librerie',
    scenario: 'La landing dell app impiega troppo a diventare interattiva su rete mobile.',
    prompt: 'Qual è la mossa più efficace?',
    options: [
      { id: 'a', label: 'Usare code splitting e lazy loading per le parti non critiche', type: 'correct' },
      { id: 'b', label: 'Unire tutte le librerie in un vendor chunk più grande', type: 'seducing_wrong' },
      { id: 'c', label: 'Ottimizzare solo le immagini senza toccare il JavaScript', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'eco-network',
    hintText: 'Ascolta cosa arriva troppo presto e non serve ancora.',
    successTitle: 'Hai alleggerito il primo canto del client.',
    successBody: 'Ridurre il JavaScript iniziale migliora tempo di interazione e percezione di velocita.',
    wrongTitle: 'Hai spostato il peso, non lo hai spezzato.',
    wrongBody: 'Un chunk gigante continua a penalizzare il caricamento iniziale e rende tutto meno flessibile.',
    incompleteBody: 'Le immagini contano, ma qui il collo di bottiglia principale resta il codice caricato troppo presto.',
    reportTags: ['performance', 'bundle', 'lazy-loading'],
  },
  {
    id: 'fe-03',
    order: 3,
    type: 'standard',
    title: 'Il Ballo delle Chiavi Gemelle',
    problem: 'Lista con key errate che scambia valori o rimonta componenti',
    scenario: 'Nella wishlist mobile gli input quantita cambiano elemento dopo un reorder.',
    prompt: 'Qual e la correzione piu solida?',
    options: [
      { id: 'a', label: 'Usare una key stabile del dominio e non l indice della lista', type: 'correct' },
      { id: 'b', label: 'Forzare un rerender completo della lista a ogni update', type: 'seducing_wrong' },
      { id: 'c', label: 'Ordinare sempre i dati prima del render', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'vista-dom',
    hintText: 'Segui quali nodi mantengono davvero identita dopo il reorder.',
    successTitle: 'Le identita sono tornate al loro posto.',
    successBody: 'In React la key descrive identita, non posizione. Un id stabile evita remount e scambi di stato.',
    wrongTitle: 'Hai corretto il sintomo, non la memoria del DOM.',
    wrongBody: 'Forzare tutto o contare sull ordine riduce il danno visibile, ma non ripara l identita dei componenti.',
    incompleteBody: 'Un ordine stabile aiuta, ma il problema riappare non appena filtri o riordini davvero la lista.',
    reportTags: ['keys', 'state-identity', 'rendering'],
  },
  {
    id: 'fe-04',
    order: 4,
    type: 'standard',
    title: 'La Cripta del Focus Perduto',
    problem: 'Modale non accessibile da tastiera / focus trap / aria mancanti',
    scenario: 'Una modale di checkout e visibile, ma chi naviga da tastiera resta intrappolato o si perde.',
    prompt: 'Che cosa va corretto davvero?',
    options: [
      { id: 'a', label: 'Gestire focus trap, ritorno focus e attributi aria corretti', type: 'correct' },
      { id: 'b', label: 'Chiudere la modale al click esterno e considerarla accessibile', type: 'seducing_wrong' },
      { id: 'c', label: 'Aggiungere tabindex agli elementi principali', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'vista-dom',
    hintText: 'Non tutto cio che si vede si puo raggiungere.',
    successTitle: 'Hai riaperto il passaggio a tastiera e screen reader.',
    successBody: 'Una modale accessibile richiede semantica, gestione del focus e ritorno ordinato al contesto precedente.',
    wrongTitle: 'La modale canta, ma non guida gli avventurieri.',
    wrongBody: 'Il click fuori o un tabindex sparso non sostituiscono il comportamento corretto di dialogo accessibile.',
    incompleteBody: 'Alcuni elementi diventano raggiungibili, ma il flusso complessivo resta fragile e confuso.',
    reportTags: ['a11y', 'focus-management', 'aria'],
  },
  {
    id: 'fe-05',
    order: 5,
    type: 'standard',
    title: 'Il Pozzo dello Spinner Infinito',
    problem: 'Errore API non gestito con spinner infinito',
    scenario: 'Nel profilo utente il caricamento resta eterno quando la chiamata fallisce o si blocca.',
    prompt: 'Qual e la soluzione migliore?',
    options: [
      { id: 'a', label: 'Gestire loading, errore, empty state e fallback chiari', type: 'correct' },
      { id: 'b', label: 'Aumentare il timeout della fetch a 60 secondi', type: 'seducing_wrong' },
      { id: 'c', label: 'Lasciare lo spinner ma con testo piu rassicurante', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'eco-network',
    hintText: 'Quando il network tace, l interfaccia deve comunque parlare.',
    successTitle: 'Hai spezzato la maledizione del caricamento eterno.',
    successBody: 'Una UI resiliente modella stati reali: successo, errore, vuoto e attesa ragionevole.',
    wrongTitle: 'Hai dato piu tempo al nulla.',
    wrongBody: 'Allungare i timeout o ammorbidire il copy non risolve la mancanza di uno stato errore vero.',
    incompleteBody: 'Il tono puo aiutare, ma senza fallback il problema di fiducia resta intatto.',
    reportTags: ['error-handling', 'async-ui', 'resilience'],
  },
  {
    id: 'fe-06',
    order: 6,
    type: 'boss',
    title: 'Il Leviatano del Checkout Spezzato',
    problem: 'Checkout mobile con widget lazy-loaded che rompe layout e doppio submit',
    scenario:
      'Nel pagamento mobile il widget entra tardi, sposta il layout e l utente riesce a premere due volte il submit.',
    prompt: 'Qual e la contromisura migliore in questo scenario combinato?',
    options: [
      { id: 'a', label: 'Riservare layout stabile e bloccare il submit durante il pending', type: 'correct' },
      { id: 'b', label: 'Precaricare sempre tutto il widget lasciando il bottone attivo', type: 'seducing_wrong' },
      { id: 'c', label: 'Aggiungere solo debounce al click', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'eco-network',
    hintText: 'Qui si combatte su due fronti: stabilita visiva e intenzione ripetuta.',
    successTitle: 'Hai sconfitto il boss del checkout in fiamme.',
    successBody: 'La soluzione migliore affronta insieme layout shift e doppio submit in un punto critico di conversione.',
    wrongTitle: 'Hai fermato una testa del mostro, l altra continuava a mordere.',
    wrongBody: 'Precaricare tutto o limitarsi al debounce lascia aperta una parte del problema e peggiora i tradeoff.',
    incompleteBody: 'Limitare il doppio click aiuta, ma senza stabilita visiva il flusso resta fragile.',
    reportTags: ['mobile-checkout', 'layout-stability', 'double-submit', 'boss-cleared'],
  },
] 

const backendDungeons: Dungeon[] = [
  {
    id: 'be-01',
    order: 1,
    type: 'standard',
    title: 'Il Bosco delle Query Infinite',
    problem: 'Endpoint Java con query N+1',
    scenario: 'Un endpoint catalogo degrada rapidamente appena aumentano relazioni e volumi.',
    prompt: 'Dove intervieni davvero?',
    options: [
      { id: 'a', label: 'Ottimizzare fetch, join o batching in modo controllato', type: 'correct' },
      { id: 'b', label: 'Aumentare RAM del servizio Java', type: 'seducing_wrong' },
      { id: 'c', label: 'Mettere cache indiscriminata sull endpoint', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'radici-sistema',
    hintText: 'Conta quante volte il bosco viene attraversato per lo stesso raccolto.',
    successTitle: 'Hai potato il N piu uno alla radice.',
    successBody: 'Il problema nasce nel pattern di accesso ai dati, non nella potenza generica della macchina.',
    wrongTitle: 'Hai nutrito il server, non il modello dati.',
    wrongBody: 'Piu risorse o cache opache possono mascherare il problema, ma non lo eliminano alla fonte.',
    incompleteBody: 'La cache puo aiutare in casi specifici, ma senza correggere il pattern il rischio rimane.',
    reportTags: ['java-performance', 'n-plus-one', 'data-access'],
  },
  {
    id: 'be-02',
    order: 2,
    type: 'standard',
    title: 'La Fiala che Non Si Chiude',
    problem: 'Worker Python con memory leak o risorse non chiuse',
    scenario: 'Un worker di backoffice funziona per ore, poi degrada e consuma troppa memoria.',
    prompt: 'Qual e la mossa piu affidabile?',
    options: [
      { id: 'a', label: 'Chiudere risorse e validare lifecycle con profiling mirato', type: 'correct' },
      { id: 'b', label: 'Riavviare il worker ogni 15 minuti', type: 'seducing_wrong' },
      { id: 'c', label: 'Aumentare la memoria del container', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'sussurro-log',
    hintText: 'Il problema non e quando nasce, ma cosa non muore mai.',
    successTitle: 'Hai chiuso i varchi da cui fuggiva memoria.',
    successBody: 'Profiling e lifecycle corretto rendono il worker stabile anche sotto carico prolungato.',
    wrongTitle: 'Hai dato piu foresta all incendio.',
    wrongBody: 'Riavvii frequenti o piu memoria ritardano il sintomo ma lasciano intatto il comportamento errato.',
    incompleteBody: 'Piu memoria puo comprare tempo, non correzione.',
    reportTags: ['python-worker', 'memory-leak', 'resource-management'],
  },
  {
    id: 'be-03',
    order: 3,
    type: 'standard',
    title: 'Il Cerchio della Prenotazione Doppia',
    problem: 'Race condition su stock o prenotazione',
    scenario: 'Gli ultimi posti disponibili vengono assegnati due volte sotto carico concorrente.',
    prompt: 'Come rendi il flusso sicuro?',
    options: [
      { id: 'a', label: 'Usare controllo concorrente, idempotenza o locking appropriato', type: 'correct' },
      { id: 'b', label: 'Introdurre sleep casuale tra i tentativi', type: 'seducing_wrong' },
      { id: 'c', label: 'Aumentare solo le repliche del database', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'radici-sistema',
    hintText: 'Due mani hanno afferrato lo stesso ramo.',
    successTitle: 'Hai ristabilito la legge del singolo possesso.',
    successBody: 'Serve una strategia di consistenza che renda la prenotazione semanticamente sicura sotto concorrenza.',
    wrongTitle: 'La foresta non rispetta ritardi casuali.',
    wrongBody: 'Il timing non e un contratto. Senza controllo di concorrenza, il problema resta aperto.',
    incompleteBody: 'Scalare il database non garantisce integrita transazionale del flusso.',
    reportTags: ['concurrency', 'idempotency', 'transactions'],
  },
  {
    id: 'be-04',
    order: 4,
    type: 'standard',
    title: 'Il Patto Spezzato dei Servizi',
    problem: 'Contratto API o evento rotto tra servizio Java e consumer Python',
    scenario: 'Un campo rinominato dal producer rompe il consumer e genera errori a catena.',
    prompt: 'Che cosa protegge davvero il sistema?',
    options: [
      { id: 'a', label: 'Versionare schema e validare compatibilita producer-consumer', type: 'correct' },
      { id: 'b', label: 'Fare parsing permissivo ignorando campi mancanti', type: 'seducing_wrong' },
      { id: 'c', label: 'Aggiungere retry al consumer', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'sussurro-log',
    hintText: 'L errore non nasce nel viaggio, ma nel linguaggio.',
    successTitle: 'Hai ricucito il patto tra i due regni.',
    successBody: 'Il contratto va reso esplicito e compatibile, non solo tollerato quando si spezza.',
    wrongTitle: 'Ritentare una menzogna non la rende vera.',
    wrongBody: 'Ignorare campi o ritentare messaggi incompatibili prolunga l instabilita senza governarla.',
    incompleteBody: 'La resilienza di trasporto non risolve una semantica di schema rotta.',
    reportTags: ['api-contract', 'schema-versioning', 'event-driven'],
  },
  {
    id: 'be-05',
    order: 5,
    type: 'standard',
    title: 'Il Portale dei Retry Impuri',
    problem: 'Timeout verso provider esterno con retry non idempotenti',
    scenario: 'Un provider esterno genera addebiti o azioni duplicate quando la richiesta viene ritentata.',
    prompt: 'Qual e la contromisura piu sicura?',
    options: [
      { id: 'a', label: 'Introdurre idempotency key e policy retry governata', type: 'correct' },
      { id: 'b', label: 'Aumentare i timeout globali del sistema', type: 'seducing_wrong' },
      { id: 'c', label: 'Spostare i retry solo sul frontend', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'radici-sistema',
    hintText: 'Un rituale ripetuto non deve evocare due volte lo stesso demone.',
    successTitle: 'Hai purificato il ciclo dei retry.',
    successBody: 'L idempotenza rende il sistema piu prevedibile quando la rete o il provider diventano ostili.',
    wrongTitle: 'Hai allungato l attesa, non la correttezza.',
    wrongBody: 'Timeout piu lunghi e retry spostati male aumentano latenza o duplicazioni senza controllarne il senso.',
    incompleteBody: 'Il client puo aiutare, ma la semantica sicura va garantita a livello di sistema.',
    reportTags: ['timeouts', 'retry-safety', 'idempotency'],
  },
  {
    id: 'be-06',
    order: 6,
    type: 'boss',
    title: 'L Idra dello Schema Ritardato',
    problem: 'Nuova versione schema da Java, worker Python non aggiornato e backlog in crescita',
    scenario: 'Il producer rilascia un nuovo schema. Il worker fallisce, il backlog sale e i retry peggiorano il caos.',
    prompt: 'Qual e la risposta piu completa?',
    options: [
      { id: 'a', label: 'Rollout compatibile con versioning, consumer aggiornato e DLQ governata', type: 'correct' },
      { id: 'b', label: 'Fermare solo il producer finche il backlog si svuota da solo', type: 'seducing_wrong' },
      { id: 'c', label: 'Aumentare solo le repliche del worker', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'sussurro-log',
    hintText: 'Qui il mostro ha tre teste: contratto, backlog e retry.',
    successTitle: 'Hai spezzato l Idra senza corrompere il flusso.',
    successBody: 'Serve coordinare compatibilita di schema, ordine di deploy e gestione del backlog.',
    wrongTitle: 'Hai combattuto volume, non semantica.',
    wrongBody: 'Scalare o fermare alla cieca puo limitare il danno, ma non corregge la rottura tra producer e consumer.',
    incompleteBody: 'Piu worker aiutano poco se continuano a processare messaggi concettualmente incompatibili.',
    reportTags: ['schema-evolution', 'consumer-compatibility', 'backlog-control', 'boss-cleared'],
  },
] 

const devopsDungeons: Dungeon[] = [
  {
    id: 'do-01',
    order: 1,
    type: 'standard',
    title: 'La Forgia delle Build Lente',
    problem: 'Dockerfile inefficiente e build lente',
    scenario: 'La pipeline CI si trascina a ogni commit, anche per modifiche minime.',
    prompt: 'Dove colpisci per primo?',
    options: [
      { id: 'a', label: 'Riorganizzare layer e caching per ridurre invalidazioni', type: 'correct' },
      { id: 'b', label: 'Usare una macchina CI piu potente', type: 'seducing_wrong' },
      { id: 'c', label: 'Comprimere i log della pipeline', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'occhio-pipeline',
    hintText: 'Guarda quale layer brucia ogni volta per un cambiamento minimo.',
    successTitle: 'Hai temprato una build degna del Paladino.',
    successBody: 'Una build ben stratificata riduce tempo, costo e attrito per ogni iterazione.',
    wrongTitle: 'Hai comprato tempo, non efficienza.',
    wrongBody: 'Piu potenza o log piu corti non risolvono l organizzazione sbagliata del Dockerfile.',
    incompleteBody: 'Ridurre rumore operativo aiuta poco se il flusso ricompila troppo.',
    reportTags: ['dockerfile', 'ci-efficiency', 'layer-cache'],
  },
  {
    id: 'do-02',
    order: 2,
    type: 'standard',
    title: 'Il Marchio di Latest',
    problem: 'Uso di latest e drift tra ambienti',
    scenario: 'Staging e produzione usano immagini con lo stesso tag ma contenuti diversi.',
    prompt: 'Come ristabilisci fiducia nel deploy?',
    options: [
      { id: 'a', label: 'Usare tag immutabili e tracciabili per ogni release', type: 'correct' },
      { id: 'b', label: 'Fare pull piu spesso dell immagine latest', type: 'seducing_wrong' },
      { id: 'c', label: 'Documentare meglio cosa dovrebbe essere latest', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'occhio-pipeline',
    hintText: 'Un nome mutevole non e una release.',
    successTitle: 'Hai dato nome e destino a ogni build.',
    successBody: 'Tag immutabili riducono drift e rendono rollback e audit molto piu affidabili.',
    wrongTitle: 'Latest resta un titolo nobile ma ingannevole.',
    wrongBody: 'Piu pull o migliore documentazione non sostituiscono un identificatore di release stabile.',
    incompleteBody: 'La documentazione aiuta il team, non il runtime.',
    reportTags: ['image-tagging', 'release-traceability', 'env-consistency'],
  },
  {
    id: 'do-03',
    order: 3,
    type: 'standard',
    title: 'Le Probe del Santuario Inquieto',
    problem: 'Probe Kubernetes configurate male',
    scenario: 'Alcuni pod ricevono traffico troppo presto, altri vengono riavviati inutilmente.',
    prompt: 'Qual e l assetto corretto?',
    options: [
      { id: 'a', label: 'Distinguere readiness, liveness e startup probe con soglie coerenti', type: 'correct' },
      { id: 'b', label: 'Disabilitare le probe nei momenti critici', type: 'seducing_wrong' },
      { id: 'c', label: 'Aumentare solo il timeout globale del cluster', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'giudizio-osservabilita',
    hintText: 'Non chiedere al servizio se e vivo quando devi sapere se e pronto.',
    successTitle: 'Hai separato vita, prontezza e risveglio.',
    successBody: 'Ogni probe ha un ruolo diverso e va tarata sul comportamento reale dell applicazione.',
    wrongTitle: 'Hai tolto il termometro al malato.',
    wrongBody: 'Disattivare o spostare tutto in un timeout unico rende il sistema meno osservabile e meno sicuro.',
    incompleteBody: 'Piu tolleranza puo ridurre il rumore, ma senza distinzione di intenti restano errori strutturali.',
    reportTags: ['k8s-probes', 'readiness', 'startup-behavior'],
  },
  {
    id: 'do-04',
    order: 4,
    type: 'standard',
    title: 'Il Falso Oracolo dell Autoscaling',
    problem: 'Autoscaling basato su metrica sbagliata',
    scenario: 'La CPU e tranquilla, ma code e latenze stanno salendo.',
    prompt: 'Qual e la mossa piu matura?',
    options: [
      { id: 'a', label: 'Scalare su una metrica che rappresenti davvero il collo di bottiglia', type: 'correct' },
      { id: 'b', label: 'Abbassare sempre la soglia CPU', type: 'seducing_wrong' },
      { id: 'c', label: 'Aumentare le repliche minime fisse', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'giudizio-osservabilita',
    hintText: 'La metrica che consola non e quella che salva.',
    successTitle: 'Hai dato all oracolo un segnale degno.',
    successBody: 'Autoscaling utile significa reagire alla pressione reale, non a una metrica comoda ma fuorviante.',
    wrongTitle: 'Hai scalato il simbolo, non la causa.',
    wrongBody: 'CPU e repliche minime possono aiutare in parte, ma non se il collo di bottiglia vive altrove.',
    incompleteBody: 'Piu repliche fisse sono una rete di sicurezza, non una strategia elastica.',
    reportTags: ['autoscaling', 'metrics', 'capacity-planning'],
  },
  {
    id: 'do-05',
    order: 5,
    type: 'standard',
    title: 'Il Reliquiario dei Secret Spezzati',
    problem: 'Secret rotation incoerente tra pod e ambienti',
    scenario: 'Alcune istanze leggono il nuovo secret, altre restano bloccate su una versione vecchia.',
    prompt: 'Come rendi la rotazione sicura?',
    options: [
      { id: 'a', label: 'Definire rotazione coordinata, rollout e verifica di propagazione', type: 'correct' },
      { id: 'b', label: 'Riavviare solo i pod che falliscono', type: 'seducing_wrong' },
      { id: 'c', label: 'Allungare la durata dei secret per ridurre il problema', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'giudizio-osservabilita',
    hintText: 'Un segreto ruotato a meta non e piu un segreto affidabile.',
    successTitle: 'Hai ricomposto il reliquiario senza spezzare il servizio.',
    successBody: 'Security e affidabilita vanno coordinate: la rotazione deve essere visibile, propagata e validata.',
    wrongTitle: 'Hai spostato il rischio nel tempo.',
    wrongBody: 'Intervenire solo sui pod falliti o allungare la durata del secret non costruisce un processo sano.',
    incompleteBody: 'Ridurre la frequenza aiuta l operativita, non la qualita della rotazione.',
    reportTags: ['secret-rotation', 'config-consistency', 'security-ops'],
  },
  {
    id: 'do-06',
    order: 6,
    type: 'boss',
    title: 'Il Tiranno del Rollout Cieco',
    problem: 'Rollout con immagine nuova, secret aggiornati e migration in ordine errato',
    scenario: 'Un deploy in produzione rompe startup e rollback. I segnali di osservabilita arrivano troppo tardi.',
    prompt: 'Qual e la risposta piu completa?',
    options: [
      { id: 'a', label: 'Orchestrare migration, config e image nell ordine corretto con guardrail osservabili', type: 'correct' },
      { id: 'b', label: 'Deployare tutto insieme fuori orario', type: 'seducing_wrong' },
      { id: 'c', label: 'Aumentare solo il numero di repliche prima del deploy', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'occhio-pipeline',
    hintText: 'Il male non e nel nuovo artefatto, ma nel suo ordine di evocazione.',
    successTitle: 'Hai guidato il rollout con giustizia e visibilita.',
    successBody: 'Il boss richiede sequenza, controlli e osservabilita sufficiente a capire quando fermarsi.',
    wrongTitle: 'Hai marciato in massa senza mappa.',
    wrongBody: 'Fuori orario o con piu repliche il sistema puo rompersi comunque se l ordine logico del deploy e sbagliato.',
    incompleteBody: 'Piu repliche attutiscono il colpo ma non correggono compatibilita e sequencing.',
    reportTags: ['rollout-order', 'migration-safety', 'observability', 'boss-cleared'],
  },
] 

const aiDungeons: Dungeon[] = [
  {
    id: 'ai-01',
    order: 1,
    type: 'standard',
    title: 'La Biblioteca dai Chunk Sfilacciati',
    problem: 'Retrieval scarso per chunking e metadata deboli',
    scenario: 'Le risposte non recuperano i documenti giusti anche quando esistono nel corpus.',
    prompt: 'Dove conviene intervenire davvero?',
    options: [
      { id: 'a', label: 'Migliorare chunking semantico e metadata per il retrieval', type: 'correct' },
      { id: 'b', label: 'Aumentare la temperatura del modello', type: 'seducing_wrong' },
      { id: 'c', label: 'Inserire piu documenti casuali nel prompt', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'grimorio-eval',
    hintText: 'Il grimorio trova male cio che e stato spezzato male.',
    successTitle: 'Hai richiamato le fonti giuste dal vuoto.',
    successBody: 'Quando retrieval e grounding sono deboli, struttura e metadati contano piu di un modello agitato.',
    wrongTitle: 'Hai acceso il modello, ma lasciato buia la biblioteca.',
    wrongBody: 'Temperatura o volume di contesto non correggono un retrieval mal progettato.',
    incompleteBody: 'Piu fonti senza ordine aumentano rumore e costo invece di migliorare grounding.',
    reportTags: ['rag-retrieval', 'chunking', 'metadata'],
  },
  {
    id: 'ai-02',
    order: 2,
    type: 'standard',
    title: 'Il Sigillo del JSON Infranto',
    problem: 'Output non strutturato quando serve JSON',
    scenario: 'Una pipeline downstream fallisce perche il modello risponde in prosa anziche in formato machine-readable.',
    prompt: 'Come rendi il flusso robusto?',
    options: [
      { id: 'a', label: 'Imporre output strutturato e validazione di schema', type: 'correct' },
      { id: 'b', label: 'Chiedere al modello di essere piu preciso', type: 'seducing_wrong' },
      { id: 'c', label: 'Pulire il testo con regex post-hoc', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'divinazione-prompt',
    hintText: 'Quando il rituale richiede forma, la forma va legata.',
    successTitle: 'Hai sigillato l output in rune leggibili dalla macchina.',
    successBody: 'Il contratto di output deve essere strutturato e verificabile, non solo sperato.',
    wrongTitle: 'Hai sperato nella disciplina dove serviva un patto.',
    wrongBody: 'Prompt piu severi o regex fragili non sostituiscono un formato imposto e validato.',
    incompleteBody: 'Le regex possono rattoppare alcuni casi, ma non rendono stabile la pipeline.',
    reportTags: ['structured-output', 'validation', 'json-discipline'],
  },
  {
    id: 'ai-03',
    order: 3,
    type: 'standard',
    title: 'Il Fantasma della Memoria Vecchia',
    problem: 'Memoria conversazionale che trascina contesto vecchio',
    scenario: 'Il sistema continua a usare vincoli obsoleti e li ripropone come se fossero ancora validi.',
    prompt: 'Qual e l intervento piu maturo?',
    options: [
      { id: 'a', label: 'Governare scope, expiry e priorita della memoria conversazionale', type: 'correct' },
      { id: 'b', label: 'Aumentare la finestra di contesto', type: 'seducing_wrong' },
      { id: 'c', label: 'Azzerare tutta la memoria a ogni turno', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'divinazione-prompt',
    hintText: 'Non tutto cio che ricorda merita ancora potere.',
    successTitle: 'Hai spezzato il giuramento del contesto obsoleto.',
    successBody: 'Una memoria utile deve avere scope e durata. Altrimenti trascina errori come verita permanenti.',
    wrongTitle: 'Hai dato piu spazio al fantasma.',
    wrongBody: 'Allargare il contesto amplifica il rumore; cancellarlo sempre elimina anche la memoria utile.',
    incompleteBody: 'Pulire tutto evita parte del problema ma distrugge continuita utile.',
    reportTags: ['memory-governance', 'context-hygiene', 'conversation-design'],
  },
  {
    id: 'ai-04',
    order: 4,
    type: 'standard',
    title: 'Il Loop dell Apprendimento Falso',
    problem: 'Loop di LLL che apprende da feedback non verificati',
    scenario: 'Un sistema auto-adattivo incorpora feedback rumorosi e peggiora nel tempo.',
    prompt: 'Qual e il guardrail migliore?',
    options: [
      { id: 'a', label: 'Separare feedback verificato e introdurre eval gate', type: 'correct' },
      { id: 'b', label: 'Accettare tutto il feedback se e numeroso', type: 'seducing_wrong' },
      { id: 'c', label: 'Spegnere completamente l apprendimento', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'grimorio-eval',
    hintText: 'Non ogni tributo del pubblico e verita addestrabile.',
    successTitle: 'Hai posto sigilli tra apprendimento e allucinazione collettiva.',
    successBody: 'Il sistema migliora quando il feedback viene governato, non solo accumulato.',
    wrongTitle: 'Hai dato al loop una folla, non una bussola.',
    wrongBody: 'Volume senza verifica amplifica errori sistemici e false correzioni.',
    incompleteBody: 'Spegnere tutto elimina il rischio, ma anche la possibilita di migliorare in modo responsabile.',
    reportTags: ['feedback-quality', 'eval-gating', 'learning-loop'],
  },
  {
    id: 'ai-05',
    order: 5,
    type: 'standard',
    title: 'Il Concilio delle Fonti Troppo Loquaci',
    problem: 'Troppe fonti nel prompt con costi e latenza eccessivi',
    scenario: 'La quality non migliora, ma i costi e i tempi di risposta crescono ad ogni chiamata.',
    prompt: 'Come riequilibri il rituale?',
    options: [
      { id: 'a', label: 'Ridurre e riordinare il contesto in base a rilevanza e costo', type: 'correct' },
      { id: 'b', label: 'Usare sempre un modello piu grande', type: 'seducing_wrong' },
      { id: 'c', label: 'Riassumere tutto in un blocco unico non verificato', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'divinazione-prompt',
    hintText: 'La saggezza non cresce con il numero delle pergamene.',
    successTitle: 'Hai alleggerito il rituale senza impoverirlo.',
    successBody: 'La selezione del contesto e uno strumento di qualita, costo e latenza insieme.',
    wrongTitle: 'Hai comprato tuono, non precisione.',
    wrongBody: 'Un modello piu grande o un riassunto non verificato non sostituiscono una scelta migliore delle fonti.',
    incompleteBody: 'Il riassunto aiuta il budget, ma puo spezzare grounding e tracciabilita.',
    reportTags: ['context-budget', 'latency-control', 'cost-optimization'],
  },
  {
    id: 'ai-06',
    order: 6,
    type: 'boss',
    title: 'Il Drago della Policy Fantasma',
    problem: 'Policy obsoleta dal RAG, memoria che rinforza l errore e risposta sicura senza citazioni',
    scenario:
      'Un assistente interno risponde con sicurezza usando una policy superata e continua a rafforzarla nel corso della conversazione.',
    prompt: 'Qual e la contromisura migliore in questo scenario composito?',
    options: [
      { id: 'a', label: 'Filtrare freshness, governare memoria e imporre citazioni strutturate', type: 'correct' },
      { id: 'b', label: 'Aumentare il numero di fonti nel prompt', type: 'seducing_wrong' },
      { id: 'c', label: 'Azzerare la memoria lasciando invariato il retrieval', type: 'incomplete' },
    ],
    correctOptionId: 'a',
    recommendedHintId: 'grimorio-eval',
    hintText: 'Tre inganni hanno formato il drago: fonte, ricordo e tono.',
    successTitle: 'Hai riportato la verita con prove e disciplina.',
    successBody: 'La risposta corretta agisce sui tre layer del problema: retrieval aggiornato, memoria governata e output fondato.',
    wrongTitle: 'Il drago amava proprio l eccesso di sicurezza senza fonti.',
    wrongBody: 'Piu fonti o memoria azzerata da sole non correggono un sistema che continua a recuperare policy vecchie.',
    incompleteBody: 'Pulire la memoria aiuta, ma se il retrieval e obsoleto l errore rientra dalla porta principale.',
    reportTags: ['grounded-ai', 'policy-freshness', 'citations', 'boss-cleared'],
  },
] 

export const gameClasses: GameClass[] = [
  {
    id: 'frontend-bardo',
    label: 'Frontend-Bardo',
    stackLabel: 'React',
    fantasyTitle: 'Custode dell Interfaccia Vivente',
    pitch: 'Incanta interfacce, placa stati ribelli e doma il caos del client.',
    intro: 'Nel regno del client, la UI trema e il DOM sussurra bug antichi.',
    palette: { accent: '#31d0ff', accentSoft: '#162f45', glow: 'rgba(49, 208, 255, 0.35)' },
    hints: [
      { id: 'vista-dom', label: 'Vista del DOM', description: 'Segui identita, focus e struttura del render.' },
      { id: 'eco-network', label: 'Eco del Network', description: 'Ascolta cosa arriva troppo presto o non arriva affatto.' },
    ],
    archetypes: {
      perfect: 'Custode dell Interfaccia Vivente',
      gritty: 'Bardo del Rilascio Critico',
      defeat: 'Apprendista del DOM Inquieto',
    },
    contentRecommendations: [
      'Checklist React per UI resiliente',
      'Guida rapida ad accessibilita e focus management',
      'Pattern per error state e loading robusti',
    ],
    dungeons: [...frontendDungeons],
  },
  {
    id: 'backend-druido',
    label: 'Backend-Druido',
    stackLabel: 'Java + Python',
    fantasyTitle: 'Custode dei Contratti di Sistema',
    pitch: 'Custodisce contratti, code, concorrenza e creature distribuite.',
    intro: 'Nelle radici dei servizi, contratti spezzati e code selvagge minacciano l equilibrio.',
    palette: { accent: '#7ee081', accentSoft: '#173324', glow: 'rgba(126, 224, 129, 0.32)' },
    hints: [
      { id: 'sussurro-log', label: 'Sussurro dei Log', description: 'L errore non parla sempre forte, ma lascia tracce.' },
      { id: 'radici-sistema', label: 'Radici del Sistema', description: 'Scava nella semantica del flusso, non solo nel sintomo.' },
    ],
    archetypes: {
      perfect: 'Custode dei Contratti di Sistema',
      gritty: 'Druido della Consistenza Ostinata',
      defeat: 'Esploratore delle Radici Corrotte',
    },
    contentRecommendations: [
      'Playbook su idempotenza e retry sicuri',
      'Mini guida su versioning di eventi e contratti',
      'Checklist per worker Python stabili nel tempo',
    ],
    dungeons: [...backendDungeons],
  },
  {
    id: 'devops-paladino',
    label: 'DevOps-Paladino',
    stackLabel: 'Docker + Kubernetes',
    fantasyTitle: 'Guardiano dei Rollout',
    pitch: 'Giura fedelta ai deploy sicuri, alle pipeline e all osservabilita.',
    intro: 'Le pipeline vacillano, i pod tremano e i rollout chiedono disciplina.',
    palette: { accent: '#f9c35f', accentSoft: '#3d2c13', glow: 'rgba(249, 195, 95, 0.28)' },
    hints: [
      { id: 'occhio-pipeline', label: 'Occhio della Pipeline', description: 'Osserva l ordine di build, release e deploy.' },
      { id: 'giudizio-osservabilita', label: 'Giudizio dell Osservabilita', description: 'Guarda se il sistema regge davvero, non solo se respira.' },
    ],
    archetypes: {
      perfect: 'Guardiano dei Rollout',
      gritty: 'Paladino del Deploy Sofferto',
      defeat: 'Scudiero delle Pipeline Inquiete',
    },
    contentRecommendations: [
      'Checklist rollout sicuri su Kubernetes',
      'Probe, readiness e startup: guida pratica',
      'Playbook su secret rotation e ambienti coerenti',
    ],
    dungeons: [...devopsDungeons],
  },
  {
    id: 'ai-stregone',
    label: 'AI-Stregone',
    stackLabel: 'RAG + LLL + RNN',
    fantasyTitle: 'Evocatore di Risposte Fondate',
    pitch: 'Evoca risposte fondate, memoria disciplinata e prompt sotto controllo.',
    intro: 'Nei grimori del contesto, fonti corrotte e memorie stanche distorcono la verita.',
    palette: { accent: '#8f8cff', accentSoft: '#241f4d', glow: 'rgba(143, 140, 255, 0.30)' },
    hints: [
      { id: 'divinazione-prompt', label: 'Divinazione del Prompt', description: 'Quando il rituale e ambiguo, il modello improvvisa.' },
      { id: 'grimorio-eval', label: 'Grimorio degli Eval', description: 'Se non sai come misuri, non sai cosa stai migliorando.' },
    ],
    archetypes: {
      perfect: 'Evocatore di Risposte Fondate',
      gritty: 'Stregone del Grounding Incombe',
      defeat: 'Novizio del Contesto Nebbioso',
    },
    contentRecommendations: [
      'Checklist RAG: freshness, chunking e metadata',
      'Prompt e structured output senza fragilita',
      'Framework minimo per eval e feedback affidabile',
    ],
    dungeons: [...aiDungeons],
  },
]

export const starterLeaderboard: LeaderboardRecord[] = [
  {
    id: 'lb-1',
    nickname: 'NinaOps',
    classId: 'devops-paladino',
    classLabel: 'DevOps-Paladino',
    score: 940,
    completionMs: 149000,
    remainingHp: 3,
    hintsUsed: 0,
    bossCleared: true,
  },
  {
    id: 'lb-2',
    nickname: 'ReactRogue',
    classId: 'frontend-bardo',
    classLabel: 'Frontend-Bardo',
    score: 880,
    completionMs: 171000,
    remainingHp: 2,
    hintsUsed: 1,
    bossCleared: true,
  },
  {
    id: 'lb-3',
    nickname: 'LogWhisperer',
    classId: 'backend-druido',
    classLabel: 'Backend-Druido',
    score: 850,
    completionMs: 176000,
    remainingHp: 2,
    hintsUsed: 1,
    bossCleared: true,
  },
  {
    id: 'lb-4',
    nickname: 'PromptHex',
    classId: 'ai-stregone',
    classLabel: 'AI-Stregone',
    score: 790,
    completionMs: 194000,
    remainingHp: 1,
    hintsUsed: 2,
    bossCleared: true,
  },
] 
